### ISSUE TITLE
cluster mode

### ISSUE THREAD

**Issue by sysword** [apache/rocketmq-mqtt#137]
Does rocketmq-mqtt support cluster mode to scale out?

**Comment by ChangingFond** [comment]
Yes，it supports naturally.

**Comment by sysword** [comment]
> Yes，it supports naturally.

thanks for your reply.
i am new to rocketmq, i wonder what's the relationship between rocketmq-mqtt and [rocketmq-proxy](https://github.com/apache/rocketmq/tree/develop/proxy), does rocketmq-proxy means to support multiple protocols ?

**Comment by DongyuanPan** [comment]
As mentioned in its introduction，[rocketmq-proxy](https://github.com/apache/rocketmq/tree/develop/proxy)  a stateless component that makes full use of the newly introduced pop consumption mechanism to achieve stateless consumption behavior. It only support RocketMQ private protocol.

**Comment by DongyuanPan** [comment]
[rocketmq-proxy](https://github.com/apache/rocketmq/tree/develop/proxy) Multi-protocol support.
With Proxy served as a traffic interface, it's convenient to implement multiple protocols upon proxy. gRPC protocol is implemented first and the customized Remoting protocol will be implemented later. HTTP/1.1 will also be taken into consideration.

The protocol in [rocketmq-proxy](https://github.com/apache/rocketmq/tree/develop/proxy)  is the communication protocol of the remoting module (communicating with broker and namesrv). Rocketmq mqtt is an application layer protocol. It implements the mqtt protocol, so that users can use rocketmq according to the mqtt protocol instead of the private protocol of rocketmq

**Comment by sysword** [comment]
thanks, this is very helpful

**Comment by DongyuanPan** [comment]
it can be closed @ShannonDing
